---
- name: Pre-deploy
  hosts: all
  become: yes
  gather_facts: yes
  gather_timeout: 20
  roles:
    - {role: pre-deploy, when: predeploy == 'true'}

- name: All stands settings
  hosts: all
  become: yes
  roles:
    - tomcat
    - web-app

- name: Only Stand-1 settings
  hosts: stand-1
  become: yes
  roles:
    - db
    - nginx
    - daemon

- name: Only Stand-3 settings
  hosts: stand-3
  become: yes
  vars:
      x: "unuselessVariable"
  roles:
    - kafka

- name: "Check fxx"
  become: yes
  hosts: stand-4
  roles:
    -  healthcheck-fxx

- name: "Restore db"
  become: yes
  hosts: stand-4
  roles:
    -  restore-db