---
- name: Create home directory
  file:
       path:  "{{ kafka_home }}"
       state: directory
       mode:  0775
       owner: mr_static
       group: mr_static


- name: Unarchiving Kafka
  unarchive:
           src:     "{{ ansible_home }}/files/kafka_2.11-2.4.1.tgz"
           dest:    "{{ kafka_home }}"
           owner:   mr_static
           group:   mr_static
  - shell: |
            mv {{ kafka_home }}/kafka_2.11-2.4.1/* {{ kafka_home }}
            rmdir  {{ kafka_home }}/kafka_2.11-2.4.1


- name: Enable ability to delete topics
  lineinfile:
            path:    "{{ kafka_home }}/config/server.properties"
            line:    delete.topic.enable=true
            create:  yes


- name: Start Zookeeper Server
  command: "{{ kafka_home }}/bin/zookeeper-server-start.sh -daemon ../config/zookeeper.properties"


- name: Start Kafka Server
  command: "{{ kafka_home }}/bin/kafka-server-start.sh -daemon ../config/server.properties"


- name: Create topics
  shell: |
      cd {{ kafka_home }}/bin
      ./kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic my-topic1
      ./kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic my-topic2
      ./kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic my-topic3
      ./kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic my-topic4