---
- name: Edit my.cnf file
  block:
    - name: Add settings after setting "pid-file"
      lineinfile:
            path: /etc/my.cnf
            line: "{{ item }}"
            insertafter: "pid-file"
            firstmatch: yes
            create: yes
      with_items:
        - validate-password=off
        - lower_case_table_names=1
    - name: Restart MySQL
      systemd:
          name:  mysqld
          state: restarted

- name: Grant access to remote "root"
  mysql_user:
        login_host: {{ inventory_hostname }}
        login_user: root
        login_password: {{ root_pass }} -- ???
        name: root
        password: root
        host: '%'
        priv: '*.*:ALL,GRANT'
-- не известно, правильно ли написан этот блок
-- то, что должно быть сделано
-- mysql -u root -p
-- mysql> CREATE USER 'root'@'%' IDENTIFIED BY 'root';
-- mysql> GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
-- mysql> quit
-- еще вариант "mysql -u root --password={{ root_pass }} --execute="SELECT stuff from stuff_table"

- name: Create schemas
  command: >
        mysql -u root --password={{ root_pass }} --execute="SELECT 1 from xDb.events"
-- тоже пока хз, как делать

